### ISSUE TITLE
Chat Rooms

### ISSUE THREAD

**Issue by emilybye16** [govyrl/ios-issues#5]
If I swipe right or click the tick, it does nothing. Is it not meant to allow me to speak to the brand I accepted?

**Comment by coolbnjmn** [comment]
Hi @emilybye16, thank you very much for your feedback. If you swipe right or hit the "checkmark" button, this is indicating you are interested in speaking to this brand/influencer. However, as of right now, that brand/influencer has to also swipe right or hit the "checkmark" button on you for a chat room to be created. We are working on ways for more direct contact, but as of right now, both parties must swipe right on the other before a conversation is begun. 

Thank you for your feedback, and please do bring up any other issues you may find!
Thanks, 
- Ben, VYRL iOS Developer
